/**
 * Language & Localization Service
 * 
 * Manages language selection (English / Hindi), persistence (localStorage & user profile),
 * and provides translation dictionary lookup for UI components.
 */

import { useState, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'hi';

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    appTitle: 'Talk With Astrologers',
    tagline: 'Vedic Astrology & Live Consultations',
    home: 'Home',
    kundli: 'Kundli',
    horoscope: 'Horoscope',
    talk: 'Talk',
    aiAstrologer: 'AI Astrologer',
    profile: 'Profile',
    login: 'Sign In',
    register: 'Register',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    phonePlaceholder: 'Enter mobile number (e.g. +919876543210)',
    otpPlaceholder: 'Enter 6-digit OTP',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify & Sign In',
    resendOtp: 'Resend OTP',
    orContinueWith: 'Or continue with',
    signInWithEmail: 'Email & Password',
    signInWithGoogle: 'Google Sign-In',
    signInWithPhone: 'Mobile Number + OTP',
    selectLanguage: 'Select Language',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    noAstrologers: 'No astrologers available right now.',
    startConsultation: 'Start Consultation',
    requestConsultation: 'Request Consultation',
    consultationFee: 'Consultation Fee',
    paymentStatus: 'Payment Status',
    paymentRequired: 'Payment Required',
    paymentPending: 'Payment Pending',
    paymentFailed: 'Payment Failed',
    paid: 'Paid',
    refundPending: 'Refund Pending',
    refunded: 'Refunded',
    partiallyRefunded: 'Partially Refunded',
    unpaid: 'Unpaid',
    proceedToPayment: 'Proceed to Secure Payment',
    paymentConfigRequired: 'Payment Gateway Configuration Required',
    paymentConfigNotice: 'Production payment processing requires secure server-side provider verification.',
    earnings: 'Expected Earnings',
    platformFee: 'Platform Fee',
    netShare: 'Net Share',
    homeOverview: 'Overview',
    consultNow: 'Consult Now',
    dailyHoroscope: 'Daily Horoscope',
    browseAstrologers: 'Browse Expert Astrologers',
    wallet: 'Wallet',
    walletBalance: 'Wallet Balance',
    addMoney: 'Add Money',
    addDemoMoney: 'Add Demo Money',
    availableBalance: 'Available Balance',
    simulatedTopupNotice: 'Interactive Prototype Top-Up. No real money will be charged.',
    depositSuccess: 'Money Added Successfully',
    insufficientWalletBalance: 'Insufficient Wallet Balance',
    topupToContinue: 'Top up your wallet to continue consultation.',
    selectTopupAmount: 'Select Top-Up Amount',
    customAmount: 'Custom Amount',
    depositNow: 'Deposit to Wallet',
    transactionHistory: 'Transaction History',
    walletHistory: 'Wallet History',
    credit: 'Credit',
    debit: 'Debit',
    balanceAfter: 'Balance After',
    noTransactions: 'No wallet transactions yet.',
    demoTransaction: 'Demo Transaction',
    walletTopup: 'Wallet Top-Up',
    consultationPayment: 'Consultation Payment',
    searchAstrologer: 'Search astrologer, specialization, or language...',
    experience: 'Experience',
    perMinute: 'per min',
    chat: 'Chat',
    voice: 'Voice',
    video: 'Video',
    myProfile: 'My Profile',
    logout: 'Sign Out',
    language: 'Language',
    notifications: 'Notifications',
    alerts: 'Alerts',
    account: 'Account',
    celestialServices: 'Celestial Services & Feature Modules',
    askAiAstrologer: 'Ask AI Astrologer',
    simulatedAiDemo: 'Simulated AI Demo',
    interactivePrototype: 'Interactive prototype demonstrating chart-based queries.',
    kundliMatching: 'Kundli Matching',
    newFeature: 'New Feature',
    kundliMatchingDesc: 'Compare two birth profiles using traditional Ashtakoota 36-Guna Milan.',
    comingSoon: 'Coming Soon',
    connectWithAstrologers: 'Connect with Astrologers — Coming Soon',
    consultationPreviewDesc: 'Preview upcoming audio call and chat consultation workflows.',
    previewFlow: 'Preview Flow',
    discoverMoreFeatures: 'Discover / More Features',
    startMatching: 'Start Matching →',
    samplePlanetaryHighlights: 'Sample Planetary Highlights',
    viewFull: 'View Full',
    numerology: 'Numerology',
    panchang: 'Panchang',
    vedicKundliChart: 'Vedic Kundli Chart',
    d1Rashi: 'D1 Rashi',
    d9Navamsha: 'D9 Navamsha',
    tapHouseToInspect: 'Tap house to inspect',
    planetaryPositionsDignity: 'Planetary Positions & Dignity',
    birthNakshatra: 'Birth Nakshatra & Archetype',
    vimsottariDasha: 'Vimshottari Dasha Periods',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    zodiacSign: 'Zodiac Sign',
    cosmicEnergies: 'Cosmic Energies',
    luckyElements: 'Lucky Elements',
    auspiciousTime: 'Auspicious Time',
    luckyColor: 'Color',
    luckyNumber: 'Number',
    rulingPlanet: 'Ruling Planet',
    astrologerDashboard: 'Astrologer Dashboard',
    adminDashboard: 'Admin Dashboard',
    clientApp: 'Client App',
    astrologerPanel: 'Astrologer Panel',
    adminPanel: 'Admin Panel',
    users: 'Users',
    astrologers: 'Astrologers',
    consultations: 'Consultations',
    payments: 'Payments',
    accounting: 'Accounting',
    reports: 'Reports',
    content: 'Content',
    settings: 'Settings',
    clients: 'Clients',
    online: 'Online',
    busy: 'Busy',
    call: 'Call',
    end: 'End',
    close: 'Close',
    send: 'Send',
    typeMessage: 'Type your message...',
    fullName: 'Full Name',
    dateOfBirth: 'Date of Birth',
    timeOfBirth: 'Time of Birth',
    placeOfBirth: 'Place of Birth',
    gender: 'Gender',
    saveAndCreateChart: 'Generate Kundli',
    welcomeTitle: 'Explore Your Vedic Destiny',
    enterBirthDetails: 'Enter Birth Details',
    exploreSample: 'Explore Sample Chart',
    continue: 'Continue',
    tithi: 'Tithi',
    nakshatra: 'Nakshatra',
    muhurat: 'Muhurat',
    lifePathNumber: 'Life Path',
    destinyNumber: 'Destiny',
    beginJourney: 'Begin Journey',
    vedicPortal: 'Vedic Portal',
    signInWithEmailDesc: 'Sign in to access your personal chart and live consultations',
    password: 'Password',
    email: 'Email',
    or: 'OR',
    backToHome: 'Back to Home',
    preparingBirthChart: 'Preparing Your Birth Chart',
    registeredBirthData: 'Registered Birth Profile Data',
    calculatingPlanetaryPositions: 'Computing planetary longitudes & house cusps',
    swissEphemerisEngineActive: 'Swiss Ephemeris WASM Engine Active',
    matchKundliWithPartner: 'Match Kundli with Partner',
    matchKundliDesc: 'Compare your Vedic chart with a partner profile using 36-Guna Milan.',
    doshaAnalysis: 'Dosha Analysis',
    manglikDosha: 'Manglik Dosha',
    kaalSarpDosha: 'Kaal Sarp Dosha',
    shaniSadeSati: 'Shani Sade Sati',
    graha: 'Graha',
    rashi: 'Rashi',
    degree: 'Degree',
    bhava: 'Bhava',
    dignity: 'Dignity',
    exalted: 'Exalted',
    ownSign: 'Own Sign',
    debilitated: 'Debilitated',
    neutral: 'Neutral',
    lord: 'Lord',
    deity: 'Deity',
    symbol: 'Symbol',
    guna: 'Gana',
    nature: 'Nature',
    significance: 'Significance',
    currentActive: 'Current Active',
    startMatchingBtn: 'Start Matching',
    quickDemoMatch: 'Quick Sample Match',
    person1Details: "First Person's Details",
    person2Details: "Second Person's Details",
    matchingScore: 'Matching Score',
    ashtakootMilan: 'Ashtakoot 36-Guna Milan',
    varna: 'Varna',
    vashya: 'Vashya',
    tara: 'Tara',
    yoni: 'Yoni',
    grahaMaitri: 'Graha Maitri',
    gana: 'Gana',
    bhakoot: 'Bhakoot',
    nadi: 'Nadi',
    numerologyReport: 'Numerology Report',
    calculateNumerology: 'Calculate Numerology',
    soulUrge: 'Soul Urge',
    personalityNumber: 'Personality',
    birthDayNumber: 'Birth Day',
    panchangPillars: 'Panchang Pillars',
    vara: 'Vara',
    yoga: 'Yoga',
    karana: 'Karana',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    moonrise: 'Moonrise',
    moonset: 'Moonset',
    auspiciousTimings: 'Auspicious Timings',
    inauspiciousTimings: 'Inauspicious Timings',
    abhijitMuhurat: 'Abhijit Muhurat',
    rahuKaal: 'Rahu Kaal',
    today: 'Today',
    askAiQuestionPlaceholder: 'Ask a question about your horoscope, career, or chart...',
    suggestedQuestions: 'Suggested Questions',
    clearChat: 'Clear Chat',
    totalRegisteredUsers: 'Total Registered Users',
    verifiedAstrologers: 'Verified Astrologers',
    activeConsultations: 'Active Consultations',
    grossRevenue: 'Gross Revenue',
    pendingAstrologers: 'Pending Astrologers',
    openTickets: 'Open Tickets',
    quickActions: 'Quick Actions',
    userManagement: 'User Management',
    astrologerManagement: 'Astrologer Management',
    consultationOperations: 'Consultation Operations',
    paymentAudits: 'Payment & Financial Audits',
    financialAccounting: 'Financial Accounting',
    systemReports: 'System Reports & Logs',
    platformContent: 'Platform Content',
    globalSettings: 'Global Platform Settings',
    approve: 'Approve',
    suspend: 'Suspend',
    activate: 'Activate',
    saveChanges: 'Save Changes',
    searchPlaceholder: 'Search by name, email, or ID...',
    status: 'Status',
    action: 'Action',
    viewKundli: 'View Kundli',
    availabilityStatus: 'Availability Status',
    availableForChat: 'Available for Chat',
    availableForVoice: 'Available for Call',
    clientsDirectory: 'Clients Directory',
    startSession: 'Start Session',
    clientNotes: 'Private Consultation Notes',
    saveNotes: 'Save Notes',
    consultationHistory: 'Consultation History',
    backToClients: 'Back to Clients',
    totalClients: 'Total Clients',
    all: 'All',
    filter: 'Filter',
    ratePerMinute: 'Rate per min',
    yearsExperience: 'Years Experience',
    reviews: 'Reviews',
    selectLanguageTitle: 'Select Your Language',
    selectLanguageSubtitle: 'Choose your preferred language for using the platform',
    continueToApp: 'Continue',
    languageChangedNotice: 'Language switched successfully',
  },
  hi: {
    appTitle: 'ज्योतिषियों से बात करें',
    tagline: 'वैदिक ज्योतिष और लाइव परामर्श',
    home: 'होम',
    kundli: 'कुंडली',
    horoscope: 'राशिफल',
    talk: 'वार्ता',
    aiAstrologer: 'एआई ज्योतिषी',
    profile: 'प्रोफाइल',
    login: 'साइन इन',
    register: 'पंजीकरण',
    emailPlaceholder: 'अपना ईमेल दर्ज करें',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    phonePlaceholder: 'मोबाइल नंबर दर्ज करें (जैसे +919876543210)',
    otpPlaceholder: '6-अंकों का ओटीपी दर्ज करें',
    sendOtp: 'ओटीपी भेजें',
    verifyOtp: 'सत्यापित करें और साइन इन करें',
    resendOtp: 'ओटीपी पुनः भेजें',
    orContinueWith: 'या इसके साथ जारी रखें',
    signInWithEmail: 'ईमेल और पासवर्ड',
    signInWithGoogle: 'गूगल साइन-इन',
    signInWithPhone: 'मोबाइल नंबर + ओटीपी',
    selectLanguage: 'भाषा चुनें',
    english: 'English',
    hindi: 'हिंदी',
    noAstrologers: 'अभी कोई ज्योतिषी उपलब्ध नहीं है।',
    startConsultation: 'परामर्श शुरू करें',
    requestConsultation: 'परामर्श का अनुरोध करें',
    consultationFee: 'परामर्श शुल्क',
    paymentStatus: 'भुगतान स्थिति',
    paymentRequired: 'भुगतान आवश्यक',
    paymentPending: 'भुगतान लंबित',
    paymentFailed: 'भुगतान विफल',
    paid: 'भुगतान संपन्न',
    refundPending: 'रिफंड लंबित',
    refunded: 'रिफंड किया गया',
    partiallyRefunded: 'आंशिक रूप से रिफंड',
    unpaid: 'अदत्त',
    proceedToPayment: 'सुरक्षित भुगतान के लिए आगे बढ़ें',
    paymentConfigRequired: 'भुगतान गेटवे कॉन्फ़िगरेशन आवश्यक',
    paymentConfigNotice: 'उत्पादन भुगतान प्रसंस्करण के लिए सर्वर-साइड सत्यापन आवश्यक है।',
    earnings: 'अनुमानित कमाई',
    platformFee: 'प्लेटफ़ॉर्म शुल्क',
    netShare: 'शुद्ध आय',
    homeOverview: 'अवलोकन',
    consultNow: 'अभी परामर्श लें',
    dailyHoroscope: 'दैनिक राशिफल',
    browseAstrologers: 'विशेषज्ञ ज्योतिषियों को देखें',
    wallet: 'वॉलेट',
    walletBalance: 'वॉलेट बैलेंस',
    addMoney: 'पैसे जोड़ें',
    addDemoMoney: 'डेमो पैसे जोड़ें',
    availableBalance: 'उपलब्ध बैलेंस',
    simulatedTopupNotice: 'इंटरएक्टिव प्रोटोटाइप टॉप-अप। कोई वास्तविक शुल्क नहीं लिया जाएगा।',
    depositSuccess: 'पैसे सफलतापूर्वक जोड़े गए',
    insufficientWalletBalance: 'अपर्याप्त वॉलेट बैलेंस',
    topupToContinue: 'परामर्श जारी रखने के लिए अपना वॉलेट रिचार्ज करें।',
    selectTopupAmount: 'टॉप-अप राशि चुनें',
    customAmount: 'अन्य राशि',
    depositNow: 'वॉलेट में जमा करें',
    transactionHistory: 'लेन-देन इतिहास',
    walletHistory: 'वॉलेट इतिहास',
    credit: 'जमा (Credit)',
    debit: 'निकासी (Debit)',
    balanceAfter: 'बाद का बैलेंस',
    noTransactions: 'अभी तक कोई वॉलेट ट्रांजैक्शन नहीं।',
    demoTransaction: 'डेमो लेन-देन',
    walletTopup: 'वॉलेट टॉप-अप',
    consultationPayment: 'परामर्श भुगतान',
    searchAstrologer: 'ज्योतिषी, विशेषज्ञता या भाषा खोजें...',
    experience: 'अनुभव',
    perMinute: 'प्रति मिनट',
    chat: 'चैट',
    voice: 'कॉल',
    video: 'वीडियो',
    myProfile: 'मेरी प्रोफाइल',
    logout: 'साइन आउट',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    alerts: 'अलर्ट्स',
    account: 'खाता',
    celestialServices: 'खगोलीय सेवाएं और फीचर मॉड्यूल',
    askAiAstrologer: 'एआई ज्योतिषी से पूछें',
    simulatedAiDemo: 'सिमुलेटेड एआई डेमो',
    interactivePrototype: 'कुंडली आधारित प्रश्नों का प्रदर्शन करने वाला इंटरैक्टिव प्रोटोटाइप।',
    kundliMatching: 'कुंडली मिलान',
    newFeature: 'नया फीचर',
    kundliMatchingDesc: 'पारंपरिक अष्टकूट 36-गुण मिलान का उपयोग करके दो जन्म प्रोफाइलों की तुलना करें।',
    comingSoon: 'शीघ्र आ रहा है',
    connectWithAstrologers: 'ज्योतिषियों से जुड़ें — शीघ्र आ रहा है',
    consultationPreviewDesc: 'आगामी ऑडियो कॉल और चैट परामर्श वर्कफ़्लो का पूर्वावलोकन करें।',
    previewFlow: 'पूर्वावलोकन प्रवाह',
    discoverMoreFeatures: 'अन्य विशेषताएं खोजें',
    startMatching: 'मिलान शुरू करें →',
    samplePlanetaryHighlights: 'नमूना ग्रहीय मुख्य विशेषताएं',
    viewFull: 'पूरा देखें',
    numerology: 'अंक ज्योतिष',
    panchang: 'पंचांग',
    vedicKundliChart: 'वैदिक कुंडली चक्र',
    d1Rashi: 'D1 राशि',
    d9Navamsha: 'D9 नवांश',
    tapHouseToInspect: 'विवरण के लिए भाव पर टैप करें',
    planetaryPositionsDignity: 'ग्रह स्थिति और गरिमा',
    birthNakshatra: 'जन्म नक्षत्र और स्वरूप',
    vimsottariDasha: 'विंशोत्तरी दशा अवधि',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    yearly: 'वार्षिक',
    zodiacSign: 'राशि',
    cosmicEnergies: 'ब्रह्मांडीय ऊर्जाएं',
    luckyElements: 'शुभ तत्व',
    auspiciousTime: 'शुभ मुहूर्त',
    luckyColor: 'रंग',
    luckyNumber: 'संख्या',
    rulingPlanet: 'स्वामी ग्रह',
    astrologerDashboard: 'ज्योतिषी डैशबोर्ड',
    adminDashboard: 'एडमिन डैशबोर्ड',
    clientApp: 'ग्राहक ऐप',
    astrologerPanel: 'ज्योतिषी पैनल',
    adminPanel: 'एडमिन पैनल',
    users: 'उपयोगकर्ता',
    astrologers: 'ज्योतिषी',
    consultations: 'परामर्श',
    payments: 'भुगतान',
    accounting: 'लेखा',
    reports: 'रिपोर्ट',
    content: 'सामग्री',
    settings: 'सेटिंग्स',
    clients: 'ग्राहक',
    online: 'ऑनलाइन',
    busy: 'व्यस्त',
    call: 'कॉल',
    end: 'समाप्त',
    close: 'बंद करें',
    send: 'भेजें',
    typeMessage: 'अपना संदेश लिखें...',
    fullName: 'पूरा नाम',
    dateOfBirth: 'जन्म तिथि',
    timeOfBirth: 'जन्म समय',
    placeOfBirth: 'जन्म स्थान',
    gender: 'लिंग',
    saveAndCreateChart: 'कुंडली बनाएं',
    welcomeTitle: 'अपनी वैदिक नियति जानें',
    enterBirthDetails: 'जन्म विवरण दर्ज करें',
    exploreSample: 'नमूना कुंडली देखें',
    continue: 'जारी रखें',
    tithi: 'तिथि',
    nakshatra: 'नक्षत्र',
    muhurat: 'मुहूर्त',
    lifePathNumber: 'मूलांक',
    destinyNumber: 'भाग्यांक',
    beginJourney: 'यात्रा प्रारंभ करें',
    vedicPortal: 'वैदिक पोर्टल',
    signInWithEmailDesc: 'अपनी कुंडली और लाइव परामर्श के लिए साइन इन करें',
    password: 'पासवर्ड',
    email: 'ईमेल',
    or: 'या',
    backToHome: 'होम पर वापस जाएं',
    preparingBirthChart: 'आपकी जन्म कुंडली तैयार हो रही है',
    registeredBirthData: 'पंजीकृत जन्म प्रोफ़ाइल डेटा',
    calculatingPlanetaryPositions: 'ग्रहों के देशांतर और भाव की गणना',
    swissEphemerisEngineActive: 'स्विस एफिमेरिस वासम इंजन सक्रिय',
    matchKundliWithPartner: 'साथी के साथ कुंडली मिलान',
    matchKundliDesc: '36-गुण मिलान का उपयोग करके अपने साथी के साथ वैदिक कुंडली की तुलना करें।',
    doshaAnalysis: 'दोष विश्लेषण',
    manglikDosha: 'मांगलिक दोष',
    kaalSarpDosha: 'कालसर्प दोष',
    shaniSadeSati: 'शनि साढ़े साती',
    graha: 'ग्रह',
    rashi: 'राशि',
    degree: 'अंश',
    bhava: 'भाव',
    dignity: 'स्थिति / गरिमा',
    exalted: 'उच्च',
    ownSign: 'स्वराशि',
    debilitated: 'नीच',
    neutral: 'सम',
    lord: 'स्वामी',
    deity: 'देवता',
    symbol: 'प्रतीक',
    guna: 'गण',
    nature: 'प्रकृति',
    significance: 'महत्व',
    currentActive: 'वर्तमान सक्रिय',
    startMatchingBtn: 'मिलान शुरू करें',
    quickDemoMatch: 'त्वरित नमूना मिलान',
    person1Details: 'पहले व्यक्ति का विवरण',
    person2Details: 'दूसरे व्यक्ति का विवरण',
    matchingScore: 'मिलान अंक',
    ashtakootMilan: 'अष्टकूट 36-गुण मिलान',
    varna: 'वर्ण',
    vashya: 'वश्य',
    tara: 'तारा',
    yoni: 'योनि',
    grahaMaitri: 'ग्रह मैत्री',
    gana: 'गण',
    bhakoot: 'भकूट',
    nadi: 'नाड़ी',
    numerologyReport: 'अंक ज्योतिष रिपोर्ट',
    calculateNumerology: 'अंक ज्योतिष की गणना करें',
    soulUrge: 'आत्मिक इच्छा',
    personalityNumber: 'व्यक्तित्व',
    birthDayNumber: 'जन्मांक',
    panchangPillars: 'पंचांग के पांच अंग',
    vara: 'वार',
    yoga: 'योग',
    karana: 'करण',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    moonrise: 'चन्द्रोदय',
    moonset: 'चन्द्रास्त',
    auspiciousTimings: 'शुभ मुहूर्त',
    inauspiciousTimings: 'अशुभ समय',
    abhijitMuhurat: 'अभिजित मुहूर्त',
    rahuKaal: 'राहु काल',
    today: 'आज',
    askAiQuestionPlaceholder: 'अपनी कुंडली, करियर या जीवन के बारे में प्रश्न पूछें...',
    suggestedQuestions: 'सुझाए गए प्रश्न',
    clearChat: 'चैट साफ़ करें',
    totalRegisteredUsers: 'कुल पंजीकृत उपयोगकर्ता',
    verifiedAstrologers: 'सत्यापित ज्योतिषी',
    activeConsultations: 'सक्रिय परामर्श',
    grossRevenue: 'सकल आय',
    pendingAstrologers: 'समीक्षाधीन ज्योतिषी',
    openTickets: 'खुले समर्थन टिकट',
    quickActions: 'त्वरित क्रियाएं',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    astrologerManagement: 'ज्योतिषी प्रबंधन',
    consultationOperations: 'परामर्श संचालन',
    paymentAudits: 'भुगतान और वित्तीय लेखा',
    financialAccounting: 'वित्तीय लेखांकन',
    systemReports: 'सिस्टम रिपोर्ट और लॉग',
    platformContent: 'प्लेटफ़ॉर्म सामग्री',
    globalSettings: 'वैश्विक सेटिंग्स',
    approve: 'स्वीकृत करें',
    suspend: 'निलंबित करें',
    activate: 'सक्रिय करें',
    saveChanges: 'परिवर्तन सहेजें',
    searchPlaceholder: 'नाम, ईमेल या आईडी से खोजें...',
    status: 'स्थिति',
    action: 'कार्रवाई',
    viewKundli: 'कुंडली देखें',
    availabilityStatus: 'उपलब्धता स्थिति',
    availableForChat: 'चैट के लिए उपलब्ध',
    availableForVoice: 'कॉल के लिए उपलब्ध',
    clientsDirectory: 'ग्राहक निर्देशिका',
    startSession: 'सत्र शुरू करें',
    clientNotes: 'गोपनीय परामर्श नोट्स',
    saveNotes: 'नोट्स सहेजें',
    consultationHistory: 'परामर्श इतिहास',
    backToClients: 'ग्राहकों की सूची पर वापस जाएं',
    totalClients: 'कुल ग्राहक',
    all: 'सभी',
    filter: 'फ़िल्टर',
    ratePerMinute: 'दर प्रति मिनट',
    yearsExperience: 'वर्षों का अनुभव',
    reviews: 'समीक्षाएं',
    selectLanguageTitle: 'अपनी भाषा चुनें',
    selectLanguageSubtitle: 'प्लेटफ़ॉर्म का उपयोग करने के लिए अपनी पसंदीदा भाषा चुनें',
    continueToApp: 'आगे बढ़ें',
    languageChangedNotice: 'भाषा सफलतापूर्वक बदल दी गई है',
  },
};

class LanguageService {
  private currentLanguage: SupportedLanguage = 'en';
  private listeners: ((lang: SupportedLanguage) => void)[] = [];

  constructor() {
    try {
      const saved = localStorage.getItem('app_language');
      if (saved === 'hi' || saved === 'en') {
        this.currentLanguage = saved;
      }
    } catch (e) {
      // ignore localStorage errors
    }
  }

  public getLanguage(): SupportedLanguage {
    return this.currentLanguage;
  }

  public setLanguage(lang: SupportedLanguage): void {
    this.currentLanguage = lang;
    try {
      localStorage.setItem('app_language', lang);
    } catch (e) {
      // ignore
    }
    this.notifyListeners();
  }

  public t(key: string): string {
    const dict = translations[this.currentLanguage] || translations.en;
    return dict[key] || translations.en[key] || key;
  }

  public subscribe(listener: (lang: SupportedLanguage) => void): () => void {
    this.listeners.push(listener);
    listener(this.currentLanguage);
    return () => {
      this.listeners = this.listeners.filter(l => l !== listener);
    };
  }

  private notifyListeners(): void {
    for (const listener of this.listeners) {
      try {
        listener(this.currentLanguage);
      } catch (e) {
        console.error('Language listener error:', e);
      }
    }
  }
}

export const languageService = new LanguageService();

export function useTranslation() {
  const [lang, setLang] = useState<SupportedLanguage>(languageService.getLanguage());

  useEffect(() => {
    return languageService.subscribe(l => setLang(l));
  }, []);

  return {
    t: (key: string) => languageService.t(key),
    language: lang,
    setLanguage: (l: SupportedLanguage) => languageService.setLanguage(l),
  };
}
